<?php
/**
 * Created by PhpStorm.
 * User: 平凡
 * Date: 2023/11/2
 * Time: 21:50
 */

namespace app\models;

use yii\base\Model;

class EntryForm extends Model
{
    public $name;
    public $email;

    public function rules()
    {
        return [
            [['name','email'],'required'],
            ['email','email']
        ]; // TODO: Change the autogenerated stub
    }

}